### ISSUE TITLE
Add an email in the README - who to report to?

### ISSUE THREAD

**Issue by abbycabs** [GuteMonik/Activismo_lenguas_EN#4]
Hey! you should have an email specific for who to raise issues with on your project. Can you add it to these two locations?

https://github.com/GuteMonik/Activismo_lenguas_EN/blob/master/README.md#participation-guidelines
https://github.com/GuteMonik/Activismo_lenguas_EN/blob/master/CODE_OF_CONDUCT.md#raising-issues-at-mozsprint

**Comment by GuteMonik** [comment]
Hi Aby
Done! :)

**Comment by abbycabs** [comment]
TY! 👍
